
:sectnums:
:sectnumlevels: 5


== Version Introduction

[**Release date: January 31, 2024**]

IvorySQL 3.1 is based on PostgreSQL 16.1 and includes various fixes from PostgreSQL 16.1, for more detailed updates and bug fixes in PostgreSQL 16.1, see the official https://www.postgresql.org/docs/release/16/[PostgreSQL 16.1 Release Notes].


== Known Issues

* None

== Enhancements

* None

== Fixed issue

* None

== Source Code

IvorySQL contains 2 main code repositories, the database IvorySQL code bin, and the IvorySQL web bin.

* IvorySQL code bin: https://github.com/IvorySQL/IvorySQL[https://github.com/IvorySQL/IvorySQL]
* IvorySQL web bin: https://github.com/IvorySQL/Ivory-www[https://github.com/IvorySQL/Ivory-www]

== Contributors

The following individuals have contributed to this release as patch authors, committers, reviewers, testers, or issue reporters.

- IvorySQL Pro development & testing team
- Xueyu Gao
- Shuntian Jiao
- Shiji Niu
- Xiangyu Liang
- Yang Tan
- Hongyuan Zhang
- Shuainan Mu
- Cary Huang
- Grant Zhou
- David Zhang
- Shoubo Wang
- Jiao Ren
- Zheng Liu
- Shanglei
- vonwind
- Weibo Han
