
:sectnums:
:sectnumlevels: 5

= PostGIS

== Overview
IvorySQL is fully compatible with PostgreSQL, allowing for seamless integration with PostGIS.

== Installation
Users can select the installation method for PostGIS that best suits their development environment from the https://postgis.net/documentation/getting_started/#installing-postgis[PostGIS installation page].

=== Source Code Installation
In addition to the installation methods provided by the PostGIS community, the IvorySQL community also offers a source code installation method, with Ubuntu 24.04 (x86_64) as the installation environment.

[NOTE]
Please ensure that **IvorySQL 5.0 or above** is installed in the environment.

** Install dependencies
[literal]
----
sudo apt install \
    docbook-xsl-ns \
    gettext \
    libgdal-dev \
    libgeos-dev \
    libjson-c-dev \
    libproj-dev \
    libprotobuf-c-dev \
    libsfcgal-dev \
    libxml2-dev \
    libxml2-utils \
    protobuf-c-compiler \
    xsltproc
----

** Install PostGIS
[literal]
----
$ wget https://download.osgeo.org/postgis/source/postgis-3.5.4.tar.gz
$ tar xvf postgis-3.5.4.tar.gz
$ cd postgis-3.5.4
$ ./configure  --with-pgconfig=/path/to/pg_config   eg: /opt/IvorySQL-5/bin/pg_config, if ivorysql installation directory is /opt/IvorySQL-5.
$ make
$ sudo make install
----
[TIP]
If configure reports PGXS error, please change --with-pgconfig parameter value and confirm the parameter value based on the installation path of IvorySQL in the environment.

== Create Extension and Verify PostGIS Version

Connect to the database with psql and execute the following commands:
[literal]
----
ivorysql=# CREATE extension postgis;
CREATE EXTENSION

ivorysql=# SELECT * FROM pg_available_extensions WHERE name = 'postgis';
  name   | default_version | installed_version |                          comment
---------+-----------------+-------------------+------------------------------------------------------------
 postgis | 3.5.4           | 3.5.4             | PostGIS geometry and geography spatial types and functions
(1 row)
----

== Using
For information about using PostGIS, please refer to the https://postgis.net/docs/manual-3.5[PostGIS 3.5 Official Documentation]
