
:sectnums:
:sectnumlevels: 5

= pg_stat_monitor

== Overview
pg_stat_monitor is a query performance monitoring extension for PostgreSQL developed by Percona. It collects statistics in a single view, including query text, timing, and wait events. It is fully compatible with IvorySQL.

== Installation

=== Prerequisites
pg_stat_monitor must be loaded at server start. Add it to `shared_preload_libraries` in `postgresql.conf`:

[literal]
----
shared_preload_libraries = 'pg_stat_monitor'
----

=== Source Code Installation

[NOTE]
Please ensure that **IvorySQL {ivorysql-version} or above** is installed and `pg_config` is available in `PATH`.

[literal]
----
$ git clone https://github.com/percona/pg_stat_monitor.git
$ cd pg_stat_monitor
$ make USE_PGXS=1
$ sudo make USE_PGXS=1 install
----

== Create Extension and Verify

Connect to the database with psql and execute the following commands:

[literal]
----
ivorysql=# CREATE EXTENSION pg_stat_monitor;
CREATE EXTENSION

ivorysql=# SELECT * FROM pg_available_extensions WHERE name = 'pg_stat_monitor';
      name       | default_version | installed_version |       comment
-----------------+-----------------+-------------------+--------------------
 pg_stat_monitor | 2.1             | 2.1               | pg_stat_monitor
----

== Query Statistics

After enabling the extension, query statistics are collected in the `pg_stat_monitor` view:

[literal]
----
ivorysql=# SELECT bucket_start_time, query, calls, total_exec_time
           FROM pg_stat_monitor
           ORDER BY total_exec_time DESC
           LIMIT 5;
----
