
:sectnums:
:sectnumlevels: 5


== Version Overview

[**Release date: July 11, 2024**]

IvorySQL 3.3, based on PostgreSQL 16.3, and Fixed a series of bugs. For a comprehensive list of updates, please visit our https://docs.ivorysql.org/[documentation site].

== Enhancements

- PostgreSQL 16.3 Enhancements

1. Restrict visibility of pg_stats_ext and pg_stats_ext_exprs entries to the table owner
2. Make ALTER FOREIGN TABLE SET SCHEMA move any owned sequences into the new schema
3. Make ALTER TABLE ... ADD COLUMN create identity/serial sequences with the same persistence as their owning tables

+

For further details, visit https://www.postgresql.org/docs/release/16.3/[PostgreSQL’s release notes].

== Fixed Issue(waiting for release notes)



== Source Code

IvorySQL's development is maintained across two main repositories:

* IvorySQL database source code: https://github.com/IvorySQL/IvorySQL
* IvorySQL official website: https://github.com/IvorySQL/Ivory-www

== Contributors(waiting for release notes)

The following individuals (in alphabetical order) have contributed to this release as patch authors, committers, reviewers, testers, or reporters of issues.

- Bei Fu
- Cary Huang
- David Zhang
- Grant Zhou
- Jiao Ren
- Lei Shang
- Leo X.M. Zeng
- Lily Wang
- Nan Jia
- Shawn Yan
- Shiji Niu
- Shoubo Wang
- Shuntian Jiao
- Xiangyu Liang
- Xinjie Lv
- Xinyuan Guo
- Xiuhua Ruan
- Xueyu Gao
- Ying Huang
- Yonghao Li
- Zheng Liu