
:sectnums:
:sectnumlevels: 5

= Reference identifier case conversion design

== Objective

- In order to meet the case compatibility of PG and Oracle's reference identifiers, ivorysql has designed three case conversion modes for reference identifiers. Select the conversion mode via the GUC parameter "identifier_case_switch".

== Scheme

=== Three modes of case conversion (interchange by default)

- If the value of the guc parameter "identifier_case_switch" is "interchange":

   	1). If the letters in the identifier referenced by the double quotation mark are all uppercase, uppercase is converted to lowercase.

      	2). If the letters in the identifier referenced by the double quotation mark are all lowercase, lowercase is converted to uppercase.

      	3). If the letters in the identifier enclosed in double quotation marks are mixed-case, the identifier is left unchanged.

=== The location of the case conversion

- If case conversion is enabled during the process of establishing a connection, you need to convert the user name and database name according to the case conversion mode.
-  After receiving the user's SQL, when san.l is parsed in SQL, the double-quoted string needs to be converted according to the case conversion mode.

=== When the database cluster is initialized

- Add the -C option to the initdb program to set the case conversion mode, and the corresponding value of -C is:

  "normal"   ------ "0"synonymy

  "interchange" ------ "1"synonymy

  "lowercase"  ------ "2"synonymy

During initialization of the database cluster, the case conversion pattern is saved to the global/pg_control file in the data directory.
