:sectnums:
:sectnumlevels: 5


== 版本概览

[**发行日期：2025年06月04日**]


IvorySQL 4.5，基于PostgreSQL 17.5，并修复了多个问题。有关更新的完整列表，请访问我们的 https://docs.ivorysql.org/[文档网站] 。

== 增强功能及问题修复

- PostgreSQL 17.5

1. 修复了在检查声明为 GB18030 编码的无效字符串时，可能发生的一字节缓冲区超读（one-byte buffer overread）问题，增强了系统处理无效编码数据的稳健性。
2. 确保对分区表上存在的自引用外键（self-referential foreign keys）进行正确处理，提升了复杂数据结构下分区表的可靠性。
3. 避免了在 brin_bloom_union() 函数中合并已压缩的 BRIN 摘要（summaries）时，可能发生的数据丢失风险，保障了索引数据的准确性。
4. 修正了在嵌套 WITH 子句中的 INSERT/UPDATE/DELETE/MERGE 命令所附带的 WITH 子句内，对外部公共表表达式（CTE）名称引用时的处理逻辑，确保了复杂查询的正确执行。
5. 修复了 ALTER TABLE ADD COLUMN 命令，以确保在添加列时，能够正确处理包含默认值的域（domain）类型，提高了表结构变更操作的准确性

+

更多细节, 请参阅 https://www.postgresql.org/docs/release/17.5/[PostgreSQL发布说明]。

- IvorySQL 4.5

1. MIPS 全平台打包支持：特性 https://github.com/IvorySQL/IvorySQL/issues/736[#736]
+
为 MIPS 架构提供多平台介质包，支持国内外主流操作系统，包括 Red Hat、Debian、麒麟、UOS、凝思等。

2. 新增IvorySQL 在线体验平台：特性 https://github.com/IvorySQL/ivorysql-wasm/issues/1[#1]
+
提供一个基于 Web 的平台，用户可直接通过浏览器界面在线体验 IvorySQL V4.5 并进行数据库交互。

3. 新增社区行为准则：特性  https://github.com/IvorySQL/IvorySQL/issues/808[#808]
+
为社区参与者明确了行为规范和期望，旨在营造一个友好且互相尊重的社区环境。

4. 更新社区贡献指南：特性 https://github.com/IvorySQL/ivorysql_docs/pull/121[#121]
+
对社区贡献流程、规范和最佳实践进行了修订与完善，方便贡献者参与。

5. 实现文档构建与网站更新自动化：特性 https://github.com/IvorySQL/ivorysql_docs/issues/115[#115]
+
通过 Pull Request (PR) 自动触发文档构建及官方网站内容更新流程。

6. 改进贡献者工作流程，通过 /assign 命令自我分配任务：特性 https://github.com/IvorySQL/ivorysql_docs/issues/109[#109]

7. IvorySQL Operator V4 适配 IvorySQL 4.5：特性 https://github.com/IvorySQL/ivory-operator/pull/79[#79]

== 源代码

IvorySQL主要包含2个代码仓库:

* IvorySQL数据库源码: https://github.com/IvorySQL/IvorySQL
* IvorySQL官方网站: https://github.com/IvorySQL/Ivory-www

== 贡献人员
以下个人（按姓氏排序）作为补丁作者、提交者、审查者、测试者或问题报告者为此版本做出了贡献。

- Cary Huang
- Denis Lussier
- Flyingbeecd
- Grant Zhou
- 高雪玉
- 矫顺田
- 纪虎林
- 梁翔宇
- 吕新杰
- 牛世继
- 潘振浩
- 隋戈
- 陶郑
- 王康
- 王守波
- 杨世华
- 赵法威
- 邹仁利
