
:sectnums:
:sectnumlevels: 5


== Version Overview

[**Release date: March 10, 2025**]

IvorySQL 4.4, based on PostgreSQL 17.4 and includes a variety of bug fixes. For a comprehensive list of updates, please visit our https://docs.ivorysql.org/[documentation site].

== Enhancements & Fixed Issue

- PostgreSQL 17.3 Enhancements

1. Harden PQescapeString and allied functions against invalidly-encoded input strings.
2. Restore auto-truncation of database and user names appearing in connection requests.
3. Exclude parallel workers from connection privilege checks and limits.
4. Drop “Lock” suffix from LWLock wait event names.
5. Fix possible re-use of stale results in window aggregates.
6. Prevent checkpoints from starting during relation truncation.

+

For further details, visit https://www.postgresql.org/docs/release/17.3/[PostgreSQL’s release notes].

- PostgreSQL 17.4 Enhancements

1. Improve behavior of libpq's quoting functions.
2. Fix small memory leak in pg_createsubscriber.
3. Fix meson build system to correctly detect availability of the bsd_auth.h system header.

+

For further details, visit https://www.postgresql.org/docs/release/17.4/[PostgreSQL’s release notes].

- IvorySQL 4.4

1. ARM64 Packaging for All Platforms: Feature https://github.com/IvorySQL/IvorySQL/issues/729[#729]
+
Provides multi-platform media packages for ARM architecture, supporting both domestic and international mainstream operating systems, including Red Hat, Debian, Kylin, UOS, and NSAR OS, etc.

2. X86 Packaging for All Platforms: Feature https://github.com/IvorySQL/IvorySQL/issues/735[#735]
+
Provides multi-platform media packages for X86 architecture, supporting both domestic and international mainstream operating systems, including Red Hat, Debian, Kylin, UOS, and NSAR OS, etc.

3. Add a new kernel architecture design document framework: Feature https://github.com/IvorySQL/IvorySQL/issues/739[#739]
+
Adds a new series on kernel architecture design, starting with Oracle compatibility. This series delves into the framework , design and implementation principles of each module, aiming to help users gain a deeper understanding of the Oracle compatibility framework.

4. Analysis of the Dual Parser Architecture Principle in the Oracle Compatibility Framework : Feature https://github.com/IvorySQL/IvorySQL/issues/740[#740]
+
Introduces the design and implementation principles of the dual parser architecture within the Oracle compatibility framework.

5. Analysis of the initdb Architecture Principle in the Oracle Compatibility Framework: Feature https://github.com/IvorySQL/IvorySQL/issues/741[#741]
+
Introduces the design and implementation principles of the initdb architecture within the Oracle compatibility framework.

6. IvorySQL official website adds chat room feature: Feature https://github.com/IvorySQL/Ivory-www/pull/133[#133]
+
Adds a chat room feature to the official website, enabling intelligent interactions and Q&A sessions related to IvorySQL.

== Source Code

IvorySQL's development is maintained across two main repositories:

* IvorySQL database source code: https://github.com/IvorySQL/IvorySQL
* IvorySQL official website: https://github.com/IvorySQL/Ivory-www

== Contributors

The following individuals (in alphabetical order) have contributed to this release as patch authors, committers, reviewers, testers, or reporters of issues.

- Alex Guo
- Cary Huang
- Denis Lussier
- Fawei Zhao
- Flyingbeecd
- Grant Zhou
- Imran Zaheer
- Kang Wang
- Lily Wang
- Mingran Feng
- Renli Zou
- Ruohang Feng
- Shawn Yan
- Shiji Niu
- Shoubo Wang
- Shuntian Jiao
- Xiangyu Liang
- Xinjie Lv
- Xueyu Gao
- Zhenhao Pan