
:sectnums:
:sectnumlevels: 5


== Version Introduction

[**Release date: November 21, 2024**]

IvorySQL 1.8 is based on PostgreSQL 14.8 and includes various fixes from PostgreSQL 14.8, for more detailed updates and bug fixes in PostgreSQL 14.8, see the official https://www.postgresql.org/docs/release/14.8/[PostgreSQL 14.8 Release Notes].

== Known Issues

* None

== Enhancements

* PostgreSQL 14.8
1. Prevent CREATE SCHEMA from defeating changes in search_path
2. Enforce row-level security policies correctly after inlining a set-returning function
3. Avoid crash when the new schema name is omitted in CREATE SCHEMA
4. Fix enabling/disabling of cloned triggers in partitioned tables
5. Disallow altering composite types that are stored in indexes
For further details, please visit PostgreSQL's release notes.

* IvorySQL 1.8
1. Add "ivorysql" database as default database
2. Support for both X86 and ARM architectures
3. Compatibility with domestic Chinese operating systems, such as Kylin V10
4. Update some IvorySQL regression tests
5. Support for more open source plugins, such as ddlx0.20, pgvector v0.8.0, and PGroonga 3.0.0.

== Source Code

IvorySQL contains 2 main code repositories, the database IvorySQL code bin, and the IvorySQL web bin.

* IvorySQL code bin: https://github.com/IvorySQL/IvorySQL[https://github.com/IvorySQL/IvorySQL]
* IvorySQL web bin: https://github.com/IvorySQL/Ivory-www[https://github.com/IvorySQL/Ivory-www]

== Contributors

The following individuals have contributed to this release as patch authors, committers, reviewers, testers, or issue reporters.

- Grant Zhou
- Jichao Ma
- Hope Gao
- Shiji Niu
- Shuntian Jiao
- Xiangyu Liang
- Xinjie Lv
- Yingze Wang
- Zhenchao Qiu
