:toc:
:toc: marco
:toc: left
:toc-title: 目录
:sectnums:
:sectnumlevels: 5
:toclevels: 5


== Versions Introduction

[**Release date: September 9, 2022**]

IvorySQL 1.5 is based on PostgreSQL 14.5 and includes various fixes and new features from IvorySQL 1.4 onwards.

This version is compatible with IvorySQL 1.4 and does not require a dump/restore for users running IvorySQL 1.X.

It contains various fixes from 14.4 onwards, specifically fixing the problem that https://www.postgresql.org/support/security/CVE-2022-2625/[extension scripts will replace objects that do not belong to the extension] could cause running arbitrary code in the victim role (possibly superuser). More details can be found in https://www.postgresql.org/docs/release/14.5/[version 14.5]

In addition, this release includes the following important fixes.

- Fixes for redoing CREATE DATABASE WAL logs on the standby server
- Support "In-Place" tablespace
- Fixes permission checking in CREATE INDEX

For updates and bug fixes in PostgreSQL 14.5, please refer to the official PostgreSQL https://www.postgresql.org/docs/release/14.5/[14.5 Release Notes].

== Feature  Introduction

- Various issues caused by version upgrade updates have been fixed.

== Known Issues

* No problems have been found.

== Fixed issues

- Fixed package variables to allow data of constant type and disallow data of pseudo-type variables. https://github.com/IvorySQL/IvorySQL/pull/162[Details]
- Tab key autocomplete in packages. https://github.com/IvorySQL/IvorySQL/pull/101[Details]

== Source Code

IvorySQL contains 2 main code repositories, the database IvorySQL code bin, and the IvorySQL blog bin:.

* IvorySQL code bin: https://github.com/IvorySQL/IvorySQL[https://github.com/IvorySQL/IvorySQL]
* IvorySQL blog bin: https://github.com/IvorySQL/Ivory-www[https://github.com/IvorySQL/Ivory-www]

== Contributors

The following individuals have contributed to this release as patch authors, committers, reviewers, testers, or issue reporters

- Asif Rehman
- Grant Zhou
- Shengbin Zhao
- Muhammad Usama

**https://github.com/IvorySQL/IvorySQL/commits/Ivory_REL_1_5[Full Update Log]**