
:sectnums:
:sectnumlevels: 5


== Versions Inroduction

[**Release Date: June 30, 2023**]

IvorySQL 2.3 is based on PostgreSQL 15.3 and includes various fixes and new features from IvorySQL 2.2 onwards.

This version is compatible with IvorySQL 2.X and does not require a dump/restore for users running IvorySQL 1.X.

IvorySQL 2.3 includes various fixes from PostgreSQL 15.3, including improved sorting performance and compression, logging and configuration enhancements, more fine-tuned logical replication options, and more. For more detailed updates and bug fixes in PostgreSQL 15.3, see the official https://www.postgresql.org/docs/release/15.3/[PostgreSQL 15.3 Release Notes] .

== Known Issues

* No issues have been found.

== Enhancements

* No feature enhancements.

== Fixed issue

* No issues fixed.

== Source Code

IvorySQL contains 2 main code repositories, the database IvorySQL code bin, and the IvorySQL blog bin.

* IvorySQL code bin: https://github.com/IvorySQL/IvorySQL[https://github.com/IvorySQL/IvorySQL]
* IvorySQL blog bin: https://github.com/IvorySQL/Ivory-www[https://github.com/IvorySQL/Ivory-www]

== Contributors

The following individuals have contributed to this release as patch authors, committers, reviewers, testers, or issue reporters.

- Cary Huang
- David Zhang
- Grant Zhou
- Yang Tan
- Jie Wang
- Shuainan Mu
- Shoubo Wang
- Jiao Ren
- Zhekai Xiao
- Huajian Jin
- Lily Wang
- Songjin Zhou
- M.Imran Zaheer

**https://github.com/IvorySQL/IvorySQL/commits/Ivory_REL_2_3[Full Update Log]**
