
:sectnums:
:sectnumlevels: 5


== Version Overview

[**Release date: Sept 10, 2025**]

IvorySQL 4.6, based on PostgreSQL 17.6 and includes a variety of bug fixes. For a comprehensive list of updates, please visit our https://docs.ivorysql.org/[documentation site].

== Enhancements & Fixed Issue

- PostgreSQL 17.6 Enhancements

1. Tighten security checks in planner estimation functions.
2. Prevent pg_dump scripts from being used to attack the user running the restore.
3. Convert newlines to spaces in names included in comments in pg_dump output.
4. Fix incorrect distance calculation in BRIN numeric_minmax_multi_ops support function.
5. Avoid regression in the size of XML input that we will accept.

+

For further details, visit https://www.postgresql.org/docs/release/17.6/[PostgreSQL’s release notes].

- IvorySQL 4.6 New Features

1. Upgrade to PG 17.6 kernel https://github.com/IvorySQL/IvorySQL/issues/859[#859]

2. MongoDB-compatible solution https://github.com/IvorySQL/IvorySQL/issues/860[#860]
+
Provide a MongoDB-compatible solution using FerretDB and DocumentDB.

3. LoongArch Packaging for All Platforms https://github.com/IvorySQL/IvorySQL/issues/738[#738] https://github.com/IvorySQL/IvorySQL/issues/829[#829]
+
Provides multi-platform media packages for LoongArch architecture, supporting both domestic and international mainstream operating systems, including Red Hat, Debian, Kylin, UOS, and NSAR OS, etc. It also supports x86, ARM, and MIPS architectures.

4. IvorySQL Online trail https://github.com/IvorySQL/ivorysql-wasm/issues/4[#4]
+
Provide users with a web-based platform to experience IvorySQL V4.6 in an online environment, enabling database interaction directly through a browser interface.

5. Containerized Deployment Support (Docker Swarm)
+
Supports deployment of standalone IvorySQL databases and high-availability clusters in Docker Swarm environments.

6. Containerized Deployment Support (Kubernetes)
+
Supports deployment of standalone IvorySQL databases and high-availability clusters on Kubernetes (K8S) using Helm.

7. https://github.com/IvorySQL/ivory-cloud/releases/tag/ivyc_4.0[IvorySQL Cloud v4.0] released.
+
The IvorySQL Cloud platform currently supports subscription management for IvorySQL v4 databases, as well as comprehensive management of its surrounding ecosystem.

- IvorySQL 4.6 Fixed Issues

1. Missing libcrypt on aarch64 platform: Issue https://github.com/IvorySQL/IvorySQL/issues/826[#826]
2. prefix test_ extension are wrongly compiled and installed while exec make and make install: Issue https://github.com/IvorySQL/IvorySQL/issues/836[#836]
3. Doc:fix some typos: Issue https://github.com/IvorySQL/ivorysql_docs/pull/143[#143]
4. Doc:Fix document errors in the installation section: Issue https://github.com/IvorySQL/ivorysql_docs/pull/143[#142]
5. Doc:Update the community contribution process: Issue https://github.com/IvorySQL/ivorysql_docs/pull/130[#130]

== Source Code

IvorySQL's development is maintained across two main repositories:

* IvorySQL database source code: https://github.com/IvorySQL/IvorySQL
* IvorySQL official website: https://github.com/IvorySQL/Ivory-www

== Contributors

The following individuals (in alphabetical order) have contributed to this release as patch authors, committers, reviewers, testers, or reporters of issues.

* caffiendo
* Cédric Villemain
* Fawei Zhao
* flyingbeecd
* Ge Sui
* Grant Zhou
* huchangqiqi
* Pedro Lopez
* RRRRhl
* Ruohang Feng
* shangwei007
* Shawn Yan
* Shaolin Chu
* Shihua Yang
* Shiji Niu
* Shuntian Jiao
* tiankongbuqi
* Xiangyu Liang
* Xinjie Lv
* Xueyu Gao
* Yanliang Lei
* Yasir Hussain Shah
* Yuan Li
* Zheng Tao
* Zhenhao Pan
* Zhuoyan Shi